name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"  # 12 AM UTC

jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          REPOSITORY: CereenaG/CereenaG
          SECTION_NAME: waka
          BLOCKS: "░▒▓█"
          TIME_RANGE: all_time
          LANG_COUNT: 5
          SHOW_TIME: true
          SHOW_TOTAL: true
          SHOW_MASKED_TIME: true
          IGNORED_LANGUAGES: "Other" 
          ONLY_LANGUAGES: "HTML, CSS, JavaScript, Java"
